### ISSUE TITLE
Watch mode only detect *.js files

### ISSUE THREAD

**Issue by splintor** [segevofer/malaby#2]
What if I want to run tests when my *.ts or *.jsx files changes?

Maybe you should run the test when the changed file has a test command configured in `malaby-config.json`.

**Comment by segevofer** [comment]
done.
you can now add this to your malaby-config: `filesToWatch: ['.json', '.jsx']`
documentation on the way.
please update your malaby `npm update -g malaby`
Thanks for opening an issue

https://github.com/segevofer/malaby/commit/6a1dbf8bd5be562ffd64ba11b4d6a5ec8190e4c1
