### ISSUE TITLE
Malaby assumes the file to run ends with `js`

### ISSUE THREAD

**Issue by splintor** [segevofer/malaby#7]
How do I run `*.tsx` test files?

The problematic line is https://github.com/segevofer/malaby/blob/master/src/malaby.js#L21

**Comment by segevofer** [comment]
@splintor 
How would you run it locally?
Is something like `node someTestRunner someTestFile.tsx` good for you?

**Comment by splintor** [comment]
Yes

**Comment by segevofer** [comment]
Ok, will get to it soon

**Comment by segevofer** [comment]
Sovled by:
https://github.com/segevofer/malaby/commit/8813a2f8f5db3406bea845bdf283d80dd07f5ed2

Thanks @splintor  for being involved 👍
